### ISSUE TITLE
Sensors fix T430

### ISSUE THREAD

**Issue by thestargateproject** [dst80/thinkfan#1]
Thinkpad T430 workaround: 

This .conf file will work:

sensors:

hwmon: /sys/class/hwmon
name: thinkpad
indices: [1]

hwmon: /sys/class/hwmon
name: coretemp
indices: [1]

fans:

tpacpi: /proc/acpi/ibm/fan
levels:

[0, 0, 40]
[1, 38, 45]
[2, 42, 50]
[3, 47, 55]
[4, 52, 60]
[5, 57, 65]
[6, 60, 72]
[7, 70, 82]
["level full-speed", 77, 32767]

**Comment by MichNLGithub** [comment]
run: find /sys/devices -type f -name "temp*_input"|sed 's/^/hwmon /g'

gives:

hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp6_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp3_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp7_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp4_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp8_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp1_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp5_input
hwmon /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon3/temp2_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp3_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp4_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp1_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp5_input
hwmon /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp2_input
hwmon /sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp1_input
hwmon /sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp2_input

Must i setup one of those sensor ?

**Comment by MichNLGithub** [comment]
.conf file:

sensors:
  - hwmon: /sys/class/hwmon
    name: thinkpad
    indices: [1]

  - hwmon: /sys/class/hwmon
    name: coretemp
    indices: [1]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0,  0, 40]
  - [1, 38, 45]
  - [2, 42, 50]
  - [3, 47, 55]
  - [4, 52, 60]
  - [5, 57, 65]
  - [6, 60, 72]
  - [7, 70, 82]
  - ["level full-speed", 77, 32767]

**Comment by thestargateproject** [comment]
run: systemctl status thinkfan.service

gives without any errors:

thinkfan.service - Thinkfan, the minimalist fan control program
     Loaded: loaded (/lib/systemd/system/thinkfan.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-10-18 13:19:53 CEST; 2min 19s ago
    Process: 4960 ExecStart=/usr/sbin/thinkfan $THINKFAN_ARGS $DAEMON_ARGS (code=exited, status=0/SUCCESS)
   Main PID: 4961 (thinkfan)
      Tasks: 1 (limit: 18999)
     Memory: 512.0K
        CPU: 31ms
     CGroup: /system.slice/thinkfan.service
             └─4961 /usr/sbin/thinkfan -c /etc/thinkfan.conf -q

okt 18 13:19:53 pop-os systemd[1]: Starting Thinkfan, the minimalist fan control program...
okt 18 13:19:53 pop-os systemd[1]: Started Thinkfan, the minimalist fan control program.
okt 18 13:19:53 pop-os thinkfan[4961]: Temperatures(bias): 45(0), 46(0) -> level 2
~

**Comment by dst80** [comment]
Hi,
thanks for your PR. Unfortunately your presented fix does not work for my Lenovo notebook (P14s).
I think the number and name of the sensors depends on which Lenovo notebook you use.
I will edit the readme.md file to make this clear.
